package ru.biblealias.models;

public enum AnswersMessage {
    INSTRUCTION,
    ENTER_TEAM_NAMES,
    SELECT_GAME_MODE,
    SELECT_ROUND_DURATION,
    ROUND_DURATION_NOT_LESS,
    ROUND_DURATION_NOT_MORE,
    HOW_MUCH_POINTS_OF_PENALTY,
    WANT_TO_EXIT_THE_SETTINGS,
    WHAT_TO_CHANGE,
    CHOOSE_LANGUAGE,

    NOW_YOU_CAN_PLAY,
    INVALID_CODE,
    YOU_DO_NOT_HAVE_ACCESS_TO_THE_BOT,
    SUCCESSFUL_AUTHORIZATION,
    WELCOME_MESSAGE,

    CANNOT_STOP_GAME_WITHOUT_STARTING,
    WINNER_TEAM,
    WINNER_TEAMS,
    DRAW,

    NUMBER_OF_POINTS,

    HELLO_TEAMS,
    YOUR_ROUND_DURATION_IS,
    IT_IS_TIME_FOR_EVERY_TEAM,
    SO_FIRST_TEAM_IS,
    GIVE_THEM_PHONE,
    ARE_YOU_READY_TO_START,

    TASK_IS,

    TURNS_TEAM_IS,
    WORD_IS,

    TIME_OF_TEAM,
    IS_OVER,
    TURN_GOES_TO_TEAM,

    TRY_NEW_GAME,
    SORRY_I_DONT_UNDERSTAND,

    THANKS_FOR_FEEDBACK,
    FEEDBACK_INSTRUCTION
}
